version: "3.8"
services:
  langchain_service:
    build: ./langchain_service
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - JOB_API_URL=${JOB_API_URL}
    env_file:
      - .env

